apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: ijwtsnmhe-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-69caf381cf.ppse.p3.openshiftapps.com/rhtap/rhtap-qe:667ff0e76d177112975432578fe7ef9a06bdf4c9@sha256:20b25c357ff1f9136d963baf9e5e9c46777678e10982452822d2c66f4f6d5677
        name: container-image  
